### ISSUE TITLE
 Error: Execution of '/usr/bin/gem install --no-rdoc --no-ri librarian-puppet' returned 1: Building native extensions.  This could take a while...

### ISSUE THREAD

**Issue by nandopacheco** [AchuM/Vagrant-Ubuntu14.04#1]
==> default: Error: Execution of '/usr/bin/gem install --no-rdoc --no-ri librarian-puppet' returned 1: Building native extensions.  This could take a while...
==> default: ERROR:  Error installing librarian-puppet:
==> default:    ERROR: Failed to build gem native extension.
==> default: 
==> default:         /usr/bin/ruby1.9.1 extconf.rb
==> default: /usr/lib/ruby/1.9.1/rubygems/custom_require.rb:36:in `require': cannot load such file -- mkmf (LoadError)
==> default:    from /usr/lib/ruby/1.9.1/rubygems/custom_require.rb:36:in`require'
==> default:    from extconf.rb:1:in `<main>'
==> default: 
==> default: 
==> default: Gem files will remain installed in /var/lib/gems/1.9.1/gems/json-1.8.2 for inspection.
==> default: Results logged to /var/lib/gems/1.9.1/gems/json-1.8.2/ext/json/ext/generator/gem_make.out
==> default: Error: /Stage[main]/Bootstrap::Modules/Package[librarian-puppet]/ensure: change from absent to present failed: Execution of '/usr/bin/gem install --no-rdoc --no-ri librarian-puppet' returned 1: Building native extensions.  This could take a while...
==> default: ERROR:  Error installing librarian-puppet:
==> default:    ERROR: Failed to build gem native extension.
==> default: 
==> default:         /usr/bin/ruby1.9.1 extconf.rb
==> default: /usr/lib/ruby/1.9.1/rubygems/custom_require.rb:36:in`require': cannot load such file -- mkmf (LoadError)
==> default:    from /usr/lib/ruby/1.9.1/rubygems/custom_require.rb:36:in `require'
==> default:    from extconf.rb:1:in`<main>'
==> default: 
==> default: 
==> default: Gem files will remain installed in /var/lib/gems/1.9.1/gems/json-1.8.2 for inspection.
==> default: Results logged to /var/lib/gems/1.9.1/gems/json-1.8.2/ext/json/ext/generator/gem_make.out
==> default: Notice: /Stage[main]/Bootstrap::Modules/Exec[librarian-puppet install]: Dependency Package[librarian-puppet] has failures: true
==> default: Warning: /Stage[main]/Bootstrap::Modules/Exec[librarian-puppet install]: Skipping because of failed dependencies
==> default: Notice: Finished catalog run in 182.23 seconds
The SSH command responded with a non-zero exit status. Vagrant
assumes that this means the command failed. The output for this command
should be in the log above. Please read the output to determine what
went wrong.

**Comment by AchuM** [comment]
Adding ruby bin to exec /opt/vagrant_ruby/bin/ Should fix this issue.

```
Exec {
    path        => "/bin/:/sbin/:/usr/bin/:/usr/sbin/:/usr/local/bin",
    path        => "/bin/:/sbin/:/usr/bin/:/usr/sbin/:/usr/local/bin:/opt/vagrant_ruby/bin/",
     environment => "HOME=/home/vagrant"
   }
```

Please try again and let me know if you still get the same result.
